services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "9000:80"
    

volumes:
  mysql_data:


# https://bwmcfuxuhqmvcqblgilv.supabase.co/storage/v1/s3

# ap-southeast-1

# 2b31916c18c0ae98be40385b8efefe9b

# 202f3d64a2d610ef5a2a9dda35e9850b8905cd52d62540672aebb280a1d1a75a